// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu0TuTEpkGLxtUw7_bZXnF_GBxpl6fLuE',
    appId: '1:407760094478:web:b79ec61f0ea0d6a165c35f',
    messagingSenderId: '407760094478',
    projectId: 'om-ornament',
    authDomain: 'om-ornament.firebaseapp.com',
    storageBucket: 'om-ornament.firebasestorage.app',
    measurementId: 'G-QSWQC75Q3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNk6BxBxAlIXXT-tOy2kH4QxR498m7Pvo',
    appId: '1:407760094478:android:c7c9bfa6f714d99465c35f',
    messagingSenderId: '407760094478',
    projectId: 'om-ornament',
    storageBucket: 'om-ornament.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtMH1pGpGte5GNPyBiWp85AaoKCWWA9Bw',
    appId: '1:407760094478:ios:212176e2ad5815e465c35f',
    messagingSenderId: '407760094478',
    projectId: 'om-ornament',
    storageBucket: 'om-ornament.firebasestorage.app',
    iosBundleId: 'com.omornament.omOrnament',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtMH1pGpGte5GNPyBiWp85AaoKCWWA9Bw',
    appId: '1:407760094478:ios:212176e2ad5815e465c35f',
    messagingSenderId: '407760094478',
    projectId: 'om-ornament',
    storageBucket: 'om-ornament.firebasestorage.app',
    iosBundleId: 'com.omornament.omOrnament',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu0TuTEpkGLxtUw7_bZXnF_GBxpl6fLuE',
    appId: '1:407760094478:web:df6522bb7e22764465c35f',
    messagingSenderId: '407760094478',
    projectId: 'om-ornament',
    authDomain: 'om-ornament.firebaseapp.com',
    storageBucket: 'om-ornament.firebasestorage.app',
    measurementId: 'G-SV36Z63G4W',
  );

}